command Pioinit lua require('platformio.pioinit').pioinit()
command Piodb lua require('platformio.piodb').piodb()
command -nargs=* Piorun lua require('platformio.piorun').piorun(<f-args>)
command -nargs=* Piocmd lua require('platformio.pioterm').piocmd({<f-args>})
command -nargs=+ Piolib lua require('platformio.piolib').piolib({<f-args>})
command -nargs=* Piomon lua require('platformio.piomon').piomon({<f-args>})
command -nargs=* Piodebug lua require('platformio.piodebug').piodebug({<f-args>})
