name: Auto Format Lua

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  stylua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check formatting
        id: check
        continue-on-error: true
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

      - name: Format Lua files
        if: steps.check.outcome == 'failure'
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .

      - name: Commit formatting changes
        if: steps.check.outcome == 'failure'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet || \
          git commit -m "style: auto format lua"

      - name: Push formatting changes
        if: steps.check.outcome == 'failure'
        run: |
          git push origin HEAD:${{ github.head_ref }}
